apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crd
  namespace: argocd
spec:
  project: default
  source:
    chart: kagent-crd
    repoURL: ghcr.io/kagent-dev/kagent/helm
    targetRevision: '0.7.13'
    helm:
      releaseName: kagent-crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
